lunarshiftapp/urls.py
from django.conf.urls import patterns, url

from lunarshiftapp import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
)

lunarshiftsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lunarshiftsite.views.home', name='home'),
	# url(r'^$', views.index, name='index'),
    url(r'^$', include('lunarshiftapp.urls')),
    url(r'^login$', 'lunarshiftapp.views.login_view'),
    url(r'^signout$', 'lunarshiftapp.views.signout_view'),
    url(r'^delete$', 'lunarshiftapp.views.delete_view'),
    url(r'^(?P<employee_type>manager|employee)/(?P<username>\w{0,30})/$', 'lunarshiftapp.views.home_view'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*about.html', 'lunarshiftapp.views.about_view'),
    url(r'.*contact.html', 'lunarshiftapp.views.contact_view'),
    url(r'^updateslider$', 'lunarshiftapp.views.updateAvailibility'),
    url(r'^addEmployee$', 'lunarshiftapp.views.addEmployee'),
    url(r'^deleteEmployee$', 'lunarshiftapp.views.deleteEmployee'),
    url(r'^deleteDayToCover$', 'lunarshiftapp.views.deleteDayToCover'),
    url(r'^addTime$', 'lunarshiftapp.views.addTime'),
	url(r'^computeSched$', 'lunarshiftapp.views.computeSchedule'),
	
)

lunarshiftapp/models.py
from django.db import models
from django.contrib.auth.models import User

MONDAY = 'M'
TUESDAY = 'T'
WEDNESDAY = 'W'
THURSDAY = 'TH'
FRIDAY = 'F'
SATURDAY = 'S'
SUNDAY = 'SU'
AVAIL_DAY_CHOICES = ((MONDAY, 'Monday'),
	(TUESDAY, 'Tuesday'), (WEDNESDAY, 'Wednesday'),
	(THURSDAY, 'Thursday'), (FRIDAY, 'Friday'),
	(SATURDAY, 'Saturday'), (SUNDAY, 'Sunday'),
	)

class Employee(models.Model):
	"""
		user: django user field consisting of a username and password.
		company: String holding company name
		isManager: bool flag for manager identification.
		setAvailaibility: bool flag if availability has been added for a user.
	"""
	user = models.ForeignKey(User, unique=True)
	company = models.CharField(max_length=100)
	isManager = models.BooleanField(default=False)
	setAvailibity = models.BooleanField(default=False)
	
	
		
	def  __unicode__(self):
		"""
		logic describing how an Employee object will be represented as a string.
		"""
		name = self.user.first_name + ' ' + self.user.last_name
		work = name + ' works for ' + self.company + ' and is a Manager ' + str(self.isManager)
		avail =  ' and has set there availibity ' + str(self.setAvailibity)
		output = work + '\n' + avail
		return output

class Availibity(models.Model):
	"""
		user: user associated with the availability entry
		AvailableDay: max 2 character string for day abbreviation
		start_time: The start of the availability
		end_time: The end of the availability
	"""
	user = models.ForeignKey(User)
	AvailibleDay = models.CharField(max_length=2, choices=AVAIL_DAY_CHOICES)
	start_time = models.TimeField('Start Time')
	end_time = models.TimeField('End Time')

	def __unicode__(self):
		"""
		String representation of Availability
		"""
		name = self.user.first_name + ' ' + self.user.last_name
		avail = ' is availible ' + self.AvailibleDay + ' at ' + str(self.start_time) + ' to ' + str(self.end_time)
		return name + avail
		
	


class Schedule(models.Model):
	"""
		user: the user associated with a schedule.
		AvailableDay
		start_time
		end_time
		monthForSched
	"""
	user = models.ForeignKey(User)
	AvailibleDay = models.CharField(max_length=2, choices=AVAIL_DAY_CHOICES)
	start_time = models.TimeField('Start Time')
	end_time = models.TimeField('End Time')
	monthForSched = models.DateField('month created', auto_now_add=True)
	


	

lunarshiftapp/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from lunarshiftapp.models import Employee, Availibity, Schedule
from django.core.exceptions import ObjectDoesNotExist
from django.core.context_processors import csrf
from django.contrib.auth.hashers import make_password
from lunarshiftapp.functionality import *

# mainly for testing routing using
from django.http import HttpResponse

# Create your views here.

def index(request, auth_form=None, user_form=None):
	return render(request,'login.html')
	# This was for testing
	# return HttpResponse("This is where the signup page will be...")

def login_view(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				# redirect to user page...successful login
				u = User.objects.get(username=username)
				try:
					e = Employee.objects.get(user=u)
					if e.isManager:
						return redirect("/manager/" + username)
					else:
						return redirect("/employee/" + username)
				except ObjectDoesNotExist:
					return HttpResponse("This user is not assigned as an employee to a company")
			else:
				# return a disabled account error message
				return HttpResponse("Error: disabled account")
		else:
			# invalid username/ password
			return HttpResponse("username or password is incorrect")

def signout_view(request):
	logout(request)
	return redirect("/")

@login_required(login_url='/')	
def home_view(request, employee_type, username):
	e = Employee.objects.get(user__username=username)
	context = {'name': e.user.first_name + " " + e.user.last_name, 'company': e.company}
	if (employee_type == "manager"):
		if e.isManager:
			scheduled = []
			for i in Employee.objects.filter(isManager=False):
				tmp = Schedule.objects.filter(user__username=i.user.username)
				if len(tmp) > 0:
					scheduled.append(i.user.username)

			context = {'name': e.user.first_name + " " + e.user.last_name, 
									'username': e.user.username,
									'company': e.company, 'employees': Employee.objects.filter(isManager=False),
									'scheduled': scheduled, 'hoursToCover': Availibity.objects.filter(user__username=e.user.username),
									'schedules': Schedule.objects.all()}
			return render(request, 'manager.html', context)
	else:
		if e.isManager == False:		
			context = {'name': e.user.first_name + " " + e.user.last_name, 
									'username': e.user.username,
									'company': e.company, 
									'hoursToCover': Availibity.objects.filter(user__username=e.user.username),
									'schedules': Schedule.objects.all()}
			return render(request, 'employee.html', context)

def addEmployee(request):
	if request.method == 'POST' and request.is_ajax():
		username = request.POST['username']
		firstname = request.POST['firstname']
		lastname = request.POST['lastname']
		password = request.POST['password']
		e = Employee.objects.get(isManager=True)
		u = User(
			username = username,
			first_name = firstname,
			last_name = lastname, 
			password = make_password(password)
		)
		u.save()
		newE = Employee(user=u, company=e.company)
		newE.save()
		return HttpResponse()

def deleteEmployee(request):
	if request.method == 'POST' and request.is_ajax():
		username = request.POST['username']
		e = Employee.objects.get(user__username=username)
		u = User.objects.get(username=username)
		e.delete()
		u.delete()
	return HttpResponse()

def deleteDayToCover(request):
	if request.method == 'POST' and request.is_ajax():
		day = request.POST['day']
		username = request.POST['username']
		a = Availibity.objects.get(user__username=username, AvailibleDay=day)
		a.delete()
		'''try:
			tmp = Availibity.objects.get(user__username=username)
		except ObjectDoesNotExist:
			e = Employee.objects.get(user__username=username)
			e.setAvailibity = False
			e.save()'''
		return HttpResponse()

def about_view(request):
	return render(request, 'about.html')

def contact_view(request):
	return render(request, 'contact.html')

def delete_view(request):
	return HttpResponse("Delete button pressed...")

def updateAvailibility(request):
	if request.method == 'POST' and request.is_ajax():
		day = request.POST['day']
		username = request.POST['username']
		startTime = request.POST['newStartTime']
		endTime = request.POST['newEndTime']
		newAv = Availibity.objects.get(user__username=username, AvailibleDay=day)
		newAv.start_time = str(startTime) + ":00"
		newAv.end_time = str(endTime) + ":00"
		newAv.save()
		return HttpResponse()

def addTime(request):
	if request.method == 'POST' and request.is_ajax():
		day = request.POST['day']
		username = request.POST['username']
		u = User.objects.get(username=username)
		e = Employee.objects.get(user__username=username)
		if e.setAvailibity == False:
			e.setAvailibity = True
		e.save()
		newAv = Availibity(
			user = u,
			AvailibleDay = day,
			start_time = "8:00",
			end_time = "17:00",
		)
		newAv.save()
		return HttpResponse()

def computeSchedule(request):
	if request.method == 'POST' and request.is_ajax():
		employeesSet = request.POST['employees']
		manager = request.POST['manager']
		#daysNeedingCoverage return a list of Schedule records, each representing a day that needs coverage
		daysNeedingCoverage = Availibity.objects.filter(user__username=manager) # manager availability is coverage	
		Schedule.objects.all().delete()
			
		#store the number of days that are in the schedule
		numberOfdays = len(Availibity.objects.filter(user__username=manager))
		#variable to store the number of hour chunks needing to be covered
	
		#return HttpResponse(numberOfdays)
		#variable for returning messages (testing)
		returnMsg = ""
		numberOfHours = 0
		poolCounter = 0
		managerCounter = 0
		#loop through each day that has coverage
		for day in daysNeedingCoverage:
			#return HttpResponse(day)
			#loop through each hour of coverage in the day
			for hour in range(day.start_time.hour, day.end_time.hour):
				#get the number of total hours in the schedule that need coverage
				numberOfHours += 1
				poolOfEmployees = []
				returnUsers = ""
				#get the set of employees who can cover this hour
				a = Availibity.objects.filter(AvailibleDay=day.AvailibleDay)#.exclude(user__username="test")
				for e in a:
					if e.start_time.hour<= hour:
						#if  len(Employee.objects.filter(user=e.user,isManager=True)) > 0:						
						#if e.user.username=='test':
						#	managerCounter += 1
							#return HttpResponse(e.user)
						#else:
								#returnUsers += str(e.user) + ","
							if str(e.user)!="test":
								poolOfEmployees.append(e)
								poolCounter += 1
				#poolOfEmployees =  Availibity.objects.filter(AvailibleDay=day.AvailibleDay)
				tmpSet = employeesSet
				#return HttpResponse(Availibity.objects.filter(AvailibleDay=day).count())
				#for x in poolOfEmployees:
				#	if x.user not in tmpSet:
				#		tmpSet.remove(x)
				if len(tmpSet) == 0 or len(poolOfEmployees)==0:
					return HttpResponse("None " + str(managerCounter))
				else:		
					newStart = str(hour) + ":00" 
					newEnd = str(hour+1) + ":00" 
					newSchedule = Schedule(user=User.objects.get(username=poolOfEmployees[0].user),AvailibleDay=day.AvailibleDay,start_time=newStart,end_time=newEnd)
					newSchedule.save()
		return HttpResponse(str(poolCounter) + " " + str(managerCounter) + " " + str(returnUsers))
				
	return HttpResponse("No schedules!")


def altComputeSchedule(request):
	if request.method == 'POST' and request.is_ajax():
		employeesSet = request.POST['employees']
		manager = request.POST['manager']
		
		compute = ComputeSchedule(employeesSet,manager)
		compute.produceSchedules([],{'M':[],'T':[],'W':[],'TH':[],'F':[],'S':[],'SU':[]},compute.k)
	return HttpResponse("Schedules!")

lunarshiftapp/templates/about.html
{% extends "base.html" %}

{% block content %}

    <!-- About Team 110 and Lunarshift -->
    <div class="container">
      <div class="jumbotron">
        <h1>lunarshift</h1>
        
        <p>Team 110 is Eugene local and University young. We strive as a small team of students who develop big products. Although we enjoy spending hours programming away, in our free time our team members enjoy:</p>
        
        <ul>
          <li><p>Playing video games</p></li>
          <li><p>Playing sweet tuba music</p></li>
          <li><p>Working on cars</p></li>
          <li><p>Hanging with friends</p></li>
          <li><p>Cooking fancy Mac n' Cheese</p></li>
        </ul>
        
        <!-- Reviews for Lunarshift -->
        <blockquote class="blockquote-reverse">
          <p>“LunarShift is out of this world. A quality product with super-quality capabilities.”</p>
          <footer>Barbra Sears, <cite title="Source Title">Eugene Times</cite></footer>
        </blockquote>
        
        <blockquote class="blockquote-reverse">
          <p>“LunarShift works for more than just businesses, it also helps the little guys and their pigs."</p>
          <footer>Old McD, <cite title="Source Title">McD Farms</cite></footer>
        </blockquote>
        <!-- End of Reviews -->

        
        <!-- Link to go to LunarShift Online Documentation / User Guide -->
        <p><a class="btn btn-primary btn-lg" role="button" href="http://lunarshift.readthedocs.org/en/latest/">View lunarshift docs &raquo;</a></p>
      </div>
    </div>

{% endblock %}

lunarshiftapp/templates/contact.html
{% extends "base.html" %}

{% block content %}

     <!-- ***** Display LunarShift Contact Information  ***** -->

    <div class="container">
      <div class="jumbotron">
        <h1>lunarshift</h1>
        <p>Team 110 is dedicated to answering your questions about our products. We have many ways to contact us. Choose the method that best suits your needs. We look forward to hearing from you. See documentation for FAQ's
        </p>
        <address>

          <strong>Team 110</strong><br>
          <abbr title="Phone"><i class="fa fa-phone"></i></abbr> (123) 456-7890<br>
          <i class="fa fa-calendar-o"></i> Monday - Friday<br>
          <i class="fa fa-clock-o"></i> 9:00 a.m. - 4:00 p.m. PT <br>
          <i class="fa fa-comment"></i> <a href="mailto:#">team110@gmail.com</a>
        </address>

        <!-- ***** Link to LunarShift Documentation  ***** -->
        <p><a class="btn btn-primary btn-lg" role="button" href="http://lunarshift.readthedocs.org/en/latest/">View lunarshift docs &raquo;</a></p>
      </div>
    </div>
{% endblock %}

lunarshiftapp/templates/employee.html
{% extends "base.html" %}

{% block content %}
    
    <div class="container">
      <!-- ***** Begin: Manager Information  ***** -->
      <div class="page-header">
        <h1>{{ name }} <small>{{ company }}</small></h1>
      </div>
      <!-- ***** End: Manager Information  ***** -->

      <!-- ***** Begin: Manager Navigation Bar  ***** -->
      <div id="content">
        <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
          <li class="active"><a href="#availability" data-toggle="tab"><i class="fa fa-clock-o"></i> Availability</a></li>
          <li><a href="#schedule" data-toggle="tab"><i class="fa fa-calendar"></i> Schedule</a></li>
        </ul>
        <!-- ***** End: Manager Navigation Bar  ***** -->
        
        <!-- ***** Begin: Manager Set Coverage  ***** -->
        <div id="my-tab-content" class="tab-content">
          <div class="tab-pane active" id="availability">
            <br>
            <p class="lead">Specify the hours you want covered here!</p>
            {% for hour in hoursToCover %}
            <div class="panel panel-info">
              <div class="panel-heading clearfix">
                <button type="button" id="{{ hour.AvailibleDay }}" class="btn btn-danger pull-right">
                  <i class="fa fa-trash-o fa-lg"></i> Delete
                </button>
                <h3 class="panel-title">{{ hour.get_AvailibleDay_display }}</h3>
              </div>
              <div class="panel-body">
                <div class="well well-lg">
                  <div id="slider{{ hour.AvailibleDay }}"></div>
                </div>
              </div>
            </div>
            {% endfor %}
            <div id="addslider"></div>

            <div class="modal fade" id="myModalTime" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="myModalLabel" align="center">
                      <i class="fa fa-clock-o fa-5x"></i>
                      <p>New Time Interval</p>
                    </h1>
                  </div>
          
                  <div class="modal-body">
                      <div class="form-group">
                        <h2>Choose a Day:</h2>
                          <select id="days" class="form-control">
                            <option>Monday</option>
                            <option>Tuesday</option>
                            <option>Wednesday</option>
                            <option>Thursday</option>
                            <option>Friday</option>
                            <option>Saturday</option>
                            <option>Sunday</option>
                          </select>
                          <span class="help-block">Choose a day you have not specified your availability yet.</span>
                      </div>
                  </div>
          
                  <div class="modal-footer">
                    <button class="btn btn-lg" data-dismiss="modal">Cancel</button>
                    <button id="addday" type="submit" data-dismiss="modal" class="btn btn-lg btn-primary">Add</button>
                  </div>
                </div>
              </div>
            </div>

            <button id="addDaytest" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModalTime">Add Day</button>
          </div>
        
          <!-- ***** End: Manager Set Coverage  ***** -->

          <!-- ***** Begin: Manager View Schedule  ***** -->
          <div class="tab-pane" id="schedule">
            <br>
            <p class="lead">Here's the work schedule!</p>
            <table class="table table-no-border">
              <th><h3>Day</h3></th>
              <th><h3>Employee</h3></th>
              <th><h3>Time</h3></th>
              <th><h3>Hours</h3></th>
              {% for sched in schedules %}
              <tr>
                <td><div class="well well-sm">{{ sched.get_AvailibleDay_display }}</div></td>
                <td><div class="well well-sm">{{ sched.user.first_name }} {{ sched.user.last_name }}</div></td>
                <td><div class="well well-sm">{{ sched.start_time }} - {{ sched.end_time }}</div></td>
                <td><div class="well well-sm">1 hr</div></td>
              </tr>
              {% endfor %}
            </table>
          </div>
          <!-- ***** End: Manager View Schedule  ***** -->


          
        </div>
      </div>
    </div> 

{% endblock %}
{% block scripts %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
          $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
              $('#paginator').datepaginator();
          });

          function convertSymbolToDay(day) {
            if (day == 'M') {
              return 'Monday';
            } else if (day == 'T') {
              return 'Tuesday';
            } else if (day == 'W') {
              return 'Wednesday';
            } else if (day == 'TH') {
              return 'Thursday';
            } else if (day == 'F') {
              return 'Friday';
            } else if (day == 'S') {
              return 'Saturday';
            } else {
              return 'Sunday';
            }
          }

          function convertDayToSymbol(day) {
            if (day == 'Monday') {
              return 'M';
            } else if (day == 'Tuesday') {
              return 'T';
            } else if (day == 'Wednesday') {
              return 'W';
            } else if (day == 'Thursday') {
              return 'TH';
            } else if (day == 'Friday') {
              return 'F';
            } else if (day == 'Saturday') {
              return 'S';
            } else {
              return 'SU';
            }
          }

          function TwoDigits(val){
            if ((val == 0) || (val == 23)) {
              return "12:00 AM";
            } else if (val < 12){
              return "0" + val + ":00 AM";
            } else if (val == 12) {
              return "12:00 PM"
            } else {
              return val - 12 + ":00 PM";
            }
          }

          var daysScheduled = new Array(7);

          function dayToNum(day) {
            if (day == "Monday"){
              return 0;
            } else if (day == "Tuesday") {
              return 1;
            } else if (day == "Wednesday") {
              return 2;
            } else if (day == "Thursday") {
              return 3;
            } else if (day == "Friday") {
              return 4;
            } else if (day == "Saturday") {
              return 5;
            } else {
              return 6;
            }
          }

          function numToDay(day) {
            if (day == 0){
              return "Monday";
            } else if (day == 1) {
              return "Tuesday";
            } else if (day == 2) {
              return "Wednesday";
            } else if (day == 3) {
              return "Thursday";
            } else if (day == 4) {
              return "Friday";
            } else if (day == 5) {
              return "Saturday";
            } else {
              return "Sunday";
            }
          }

          $("#availability").on("click", ".btn-danger", function(e) {
            var day = this.id;
            var dayNotSym = convertSymbolToDay(day);
            var num = dayToNum(dayNotSym);
            daysScheduled[num] = 0;
            var panel = $(this).parent().parent();
            panel.fadeOut(400, function(){
              panel.remove();
            });
            $.ajax({
              type: "POST",
              url: "/deleteDayToCover",
              data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                day: day, 
                username: "{{ username }}",
              },
              /*error: function(xhr, textStatus, errorThrown) {
                alert("Please report this error: "+errorThrown+xhr.status+xhr.responseText);
              }*/
            });
          });

          $("#availability").on("click", "#addday", function(e) {
            var day = $("#days :selected").text();
            if (daysScheduled[dayToNum(day)] == 1) {
              $(this).parent().parent().effect("shake");
              return false;
            } else {
              var symbol = convertDayToSymbol(day);
              daysScheduled[dayToNum(day)] = 1;
              slider = "slider" + symbol;

              $.ajax({
                type: "POST",
                url: "/addTime",
                data: {
                  csrfmiddlewaretoken: '{{ csrf_token }}',
                  username: "{{ username }}",
                  day: symbol,
                },
                /*error: function(xhr, textStatus, errorThrown) {
                  alert("Please report this error: "+errorThrown+xhr.status+xhr.responseText);
                }*/
              });

              $(slider).dateRangeSlider({
                bounds: {min: new Date(2013, 0, 1), max: new Date(2013, 0, 1, 23, 59, 59)},
                defaultValues: {min: new Date(2013, 0, 1, 8), max: new Date(2013, 0, 1, 17)},
                formatter: function(value){
                  var hours = value.getHours(),
                  minutes = value.getMinutes();
                  return TwoDigits(hours);
                }
              });

              $("#addslider").append("<div class='panel panel-info'>" +
                                    "<div class='panel-heading clearfix'>" + 
                                      "<button type='button'" + "id='" + symbol + "' class='btn btn-danger pull-right'>" +
                                        "<i class='fa fa-trash-o fa-lg'></i> Delete" +
                                      "</button>" +
                                      "<h3 class='panel-title'>" + day + "</h3>" +
                                    "</div>" +
                                    "<div class='panel-body'>" +
                                      "<div class='well well-lg'>" + "<div id='" + slider + "'></div>" +
                                      "</div>" +
                                    "</div>" +
                                  "</div>");
            
            $("#"+slider).dateRangeSlider({
              bounds: {min: new Date(2013, 0, 1), max: new Date(2013, 0, 1, 23, 59, 59)},
              defaultValues: {min: new Date(2013, 0, 1, 8), max: new Date(2013, 0, 1, 17)},
              formatter: function(value){
                var hours = value.getHours(),
                minutes = value.getMinutes();
                return TwoDigits(hours);
              }
            });

            $("#"+slider).bind("userValuesChanged", function(e, data){
              console.log("Values just changed. min: " + data.values.min + " max: " + data.values.max);
              $.ajax({
                type: "POST",
                url: "/updateslider",
                data: {
                  csrfmiddlewaretoken: '{{ csrf_token }}',
                  username: "{{ username }}",
                  day: symbol,
                  newStartTime: data.values.min.getHours(),
                  newEndTime: data.values.max.getHours(),
              },
              error: function(xhr, textStatus, errorThrown) {
                alert("Please report this error: "+errorThrown+xhr.status+xhr.responseText);
              }
             });
            });

            } // end else
          });

          {% for i in hoursToCover %}
          daysScheduled[dayToNum("{{ i.get_AvailibleDay_display }}")] = 1;
          $("#slider{{ i.AvailibleDay }}").dateRangeSlider({
            bounds: {min: new Date(2013, 0, 1), max: new Date(2013, 0, 1, 23, 59, 59)},
            defaultValues: {min: new Date(2013, 0, 1, {{ i.start_time.hour }}), max: new Date(2013, 0, 1, {{ i.end_time.hour }})},
            formatter: function(value){
              var hours = value.getHours(),
              minutes = value.getMinutes();
              return TwoDigits(hours);
            }
          });

          $("#slider{{ i.AvailibleDay }}").bind("userValuesChanged", function(e, data){
            console.log("Values just changed. min: " + data.values.min + " max: " + data.values.max);
            $.ajax({
              type: "POST",
              url: "/updateslider",
              data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                username: "{{ username }}",
                day: "{{ i.AvailibleDay }}",
                newStartTime: data.values.min.getHours(),
                newEndTime: data.values.max.getHours(),
              },
              error: function(xhr, textStatus, errorThrown) {
                alert("Please report this error: "+errorThrown+xhr.status+xhr.responseText);
              }
            });
          });
          {% endfor %}
      });
      </script> 
    
{% endblock %}